{% set version = '0.10.0' %}

package:
  name: entityd-config-recipe
  version: {{version}}

source:
  # Test build with: path: ../..
  hg_url: ssh://hg@bitbucket.org/abilisoft/entityd
  hg_tag: rel/{{version}}

build:
  number: 0

about:
  home: https://abilisoft.com/
  license: Proprietary
