# Conda environment specification.
#
# To create a new development environment called "foo" use the
# ``conda env`` command in the current working directory::
#
#    $ conda env create -n foo
#
# To update an existing environment with these dependencies invoke::
#
#    $ conda env update -n foo
#
# In order to run the entityd package from the current directory as well
# you need to use pip to install it as editable::
#
#    $ pip install -e .

dependencies:

  # runtime
  - python >=3.4,<3.5
  - cffi
  - pyzmq
  - msgpack-python
  - syskit
  - requests >=2.11.1
  - pyyaml
  - act
  - kube >=0.8.0,<0.10.0
  - python-cobe >=0.2.0
  - docker-py

  # development
  - pytest
  - pytest-cov
  - pytest-logbook
  - pylint
  - pylint-abilisoft
  - coverage
  - invoke >=0.13.0,<0.14.0
  - pip
