{% set version="0.3.1" %}

package:
  name: entityd-conf
  version: {{ version }}

source:
  hg_url: https://bitbucket.org/abilisoft/entityd
  hg_tag: "rel/{{ version }}"

build:
  number: 1

requirements:
  build:
    - config-files
  run:
    - config-files

about:
  home: https://abilisoft.com
  license: proprietary
