{% set version = '0.7.0' %}

package:
  name: entityd
  version: {{version}}

source:
  # Test build with: path: ../..
  hg_url: ssh://hg@bitbucket.org/abilisoft/entityd
  hg_tag: rel/{{version}}

build:
  number: 0

requirements:
  build:
    - python >=3.4,<3.5
    - setuptools
  run:
    - python >=3.4,<3.5
    - setuptools
    - pyzmq
    - msgpack-python
    - syskit
    - supervisord
    - requests
    - pyyaml
    - act
    - entityd-config =={{version}}
    - kube <0.2.0

test:
  requires:
    - pytest
    - pytest-capturelog
    - pytest-cov
    - pytest-logbook
  commands:
    - entityd --version
    - py.test --cov-report='' $SRC_DIR
  imports:
    - entityd

about:
  home: https://abilisoft.com
  license: proprietary
