{% set version = '0.4.1' %}

package:
  name: entityd
  version: {{version}}

source:
  hg_url: https://bitbucket.org/abilisoft/entityd
  hg_tag: rel/{{version}}

build:
  number: 0

requirements:
  build:
    - python >=3.4,<3.5
    - setuptools
  run:
    - python >=3.4,<3.5
    - setuptools
    - pyzmq
    - msgpack-python
    - syskit
    - supervisord
    - requests
    - pyyaml
    - act
    - entityd-config

test:
  requires:
    - pytest
    - pytest-capturelog
    - pytest-cov
  commands:
    - entityd --version
    - py.test --cov-report='' $SRC_DIR
  imports:
    - entityd

about:
  home: https://abilisoft.com
  license: proprietary
